config/routes.rb
Rails.application.routes.draw do
  
  resources :cities
  resources :provinces
  resources :wx_users
  resources :admin

end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/province.rb
class Province < ActiveRecord::Base

	validates :name, length: { maximum: 1,message: "内容太长" }
end

app/models/wx_user.rb
class WxUser < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :province_id)
    end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: '数据添加成功！' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: '数据更新成功！' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: '数据删除成功！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name)
    end
end

app/controllers/wx_users_controller.rb
class WxUsersController < ApplicationController
  before_action :set_wx_user, only: [:show, :edit, :update, :destroy]

  # GET /wx_users
  # GET /wx_users.json
  def index
    @wx_users = WxUser.all
  end

  # GET /wx_users/1
  # GET /wx_users/1.json
  def show
  end

  # GET /wx_users/new
  def new
    @wx_user = WxUser.new
  end

  # GET /wx_users/1/edit
  def edit
  end

  # POST /wx_users
  # POST /wx_users.json
  def create
    @wx_user = WxUser.new(wx_user_params)

    respond_to do |format|
      if @wx_user.save
        format.html { redirect_to @wx_user, notice: 'Wx user was successfully created.' }
        format.json { render :show, status: :created, location: @wx_user }
      else
        format.html { render :new }
        format.json { render json: @wx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wx_users/1
  # PATCH/PUT /wx_users/1.json
  def update
    respond_to do |format|
      if @wx_user.update(wx_user_params)
        format.html { redirect_to @wx_user, notice: 'Wx user was successfully updated.' }
        format.json { render :show, status: :ok, location: @wx_user }
      else
        format.html { render :edit }
        format.json { render json: @wx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wx_users/1
  # DELETE /wx_users/1.json
  def destroy
    @wx_user.destroy
    respond_to do |format|
      format.html { redirect_to wx_users_url, notice: 'Wx user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wx_user
      @wx_user = WxUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wx_user_params
      params.require(:wx_user).permit(:name, :mobile, :wx_name, :money)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/wx_users_helper.rb
module WxUsersHelper
end

app/views/cities/_form.html.erb
<%= form_for @city, :html => { :class => "form-horizontal city" } do |f| %>

  <% if @city.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @city.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :province_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :province_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:province_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cities_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/cities/edit.html.erb
<%- model_class = City -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cities/index.html.erb
<%- model_class = City -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:province_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= link_to city.id, city_path(city) %></td>
        <td><%= city.name %></td>
        <td><%= city.province_id %></td>
        <td><%=l city.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_city_path(city), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      city_path(city),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_city_path,
            :class => 'btn btn-primary' %>

app/views/cities/new.html.erb
<%- model_class = City -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cities/show.html.erb
<%- model_class = City -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @city.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:province_id) %>:</strong></dt>
  <dd><%= @city.province_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              cities_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_city_path(@city), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              city_path(@city),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/provinces/_form.html.erb
<%= form_for @province, :html => { :class => "form-horizontal" } do |f| %>

  <% if @province.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @province.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-1' ,:value=>'士大夫士大夫到沙发'%>
    <div class="col-lg-4">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                provinces_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/provinces/edit.html.erb
<%- model_class = Province -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/provinces/index.html.erb
<%- model_class = Province -%>
<div class="row">
    <div class="col-lg-2">
        <h1 class="page-header">省份城市管理 </h1>
    </div class="col-lg-1">
    <div><h1 class="page-header"><%= link_to t('.new', :default => "新增记录"),new_province_path,:class => 'btn btn-primary' %></h1></div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            <label><input type="search" class="form-control" placeholder="名称" size="8" ></label>
            &nbsp;&nbsp;
            &nbsp;&nbsp;<button type="button" class="btn btn-primary" aria-hidden="true">查询</button>
            &nbsp;&nbsp;<button type="button" class="btn btn-warning">导出</button>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-striped table-hover">
                    <thead>
                      <tr>
                        <th><%= model_class.human_attribute_name(:id) %></th>
                        <th><%= model_class.human_attribute_name(:name) %></th>
                        <th><%= model_class.human_attribute_name(:created_at) %></th>
                        <th><%=t '.actions', :default => t("helpers.actions") %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @provinces.each do |province| %>
                        <tr>
                          <td><%= link_to province.id, province_path(province) %></td>
                          <td><%= province.name %></td>
                          <td><%= province.created_at %></td>
                          <td>
                            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                        edit_province_path(province), :class => 'btn btn-default btn-xs' %>
                            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                        province_path(province),
                                        :method => :delete,
                                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                        :class => 'btn btn-xs btn-danger' %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/provinces/new.html.erb
<%- model_class = Province -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/provinces/show.html.erb
<%- model_class = Province -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @province.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              provinces_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_province_path(@province), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              province_path(@province),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/wx_users/_form.html.erb
<%= form_for @wx_user, :html => { :class => "form-horizontal wx_user" } do |f| %>

  <% if @wx_user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@wx_user.errors.count, "error") %> prohibited this wx_user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @wx_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :mobile, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mobile, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mobile) %>
  </div>
  <div class="form-group">
    <%= f.label :wx_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :wx_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:wx_name) %>
  </div>
  <div class="form-group">
    <%= f.label :money, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :money, :class => 'form-control' %>
    </div>
    <%=f.error_span(:money) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                wx_users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/wx_users/edit.html.erb
<%- model_class = WxUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/wx_users/index.html.erb
<%- model_class = WxUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:wx_name) %></th>
      <th><%= model_class.human_attribute_name(:money) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @wx_users.each do |wx_user| %>
      <tr>
        <td><%= link_to wx_user.id, wx_user_path(wx_user) %></td>
        <td><%= wx_user.name %></td>
        <td><%= wx_user.mobile %></td>
        <td><%= wx_user.wx_name %></td>
        <td><%= wx_user.money %></td>
        <td><%=l wx_user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_wx_user_path(wx_user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      wx_user_path(wx_user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_wx_user_path,
            :class => 'btn btn-primary' %>

app/views/wx_users/new.html.erb
<%- model_class = WxUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/wx_users/show.html.erb
<%- model_class = WxUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @wx_user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @wx_user.mobile %></dd>
  <dt><strong><%= model_class.human_attribute_name(:wx_name) %>:</strong></dt>
  <dd><%= @wx_user.wx_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:money) %>:</strong></dt>
  <dd><%= @wx_user.money %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              wx_users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_wx_user_path(@wx_user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              wx_user_path(@wx_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>